# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/ugrad/ugrad003/roctosycl/rocFFT;/home/ugrad/ugrad003/roctosycl/rocFFT/builddir")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/debian/postinst;/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/debian/prerm")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "hip-rocclr (>= 3.5.0)")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "rocfft-maintainer@amd.com")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "rocfft built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "/home/ugrad/ugrad003/roctosycl/rocFFT;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/opt/rocm")
set(CPACK_MODULE_PATH "/opt/rocm/share/rocm/cmake;/home/ugrad/ugrad003/roctosycl/rocFFT/cmake;/home/ugrad/ugrad003/roctosycl/rocFFT/cmake")
set(CPACK_NSIS_DISPLAY_NAME "rocfft 1.0.13.1188-65699a2")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "rocfft")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ROCm FFT library")
set(CPACK_PACKAGE_FILE_NAME "rocfft-1.0.13.1188-65699a2-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "rocfft 1.0.13.1188-65699a2")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "rocfft 1.0.13.1188-65699a2")
set(CPACK_PACKAGE_NAME "rocfft")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Advanced Micro Devices, Inc")
set(CPACK_PACKAGE_VERSION "1.0.13.1188-65699a2")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "13")
set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/rocm")
set(CPACK_RESOURCE_FILE_LICENSE "/home/ugrad/ugrad003/roctosycl/rocFFT/library/../LICENSE.md")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.17/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "${CPACK_PACKAGING_INSTALL_PREFIX};${CPACK_PACKAGING_INSTALL_PREFIX}/include;${CPACK_PACKAGING_INSTALL_PREFIX}/lib;${CPACK_PACKAGING_INSTALL_PREFIX}/lib/cmake")
set(CPACK_RPM_PACKAGE_AUTOREQPROV "Off")
set(CPACK_RPM_PACKAGE_RELOCATABLE "Off")
set(CPACK_RPM_PACKAGE_REQUIRES "hip-rocclr >= 3.5.0")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/debian/postinst")
set(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE "/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/debian/prerm")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/ugrad/ugrad003/roctosycl/rocFFT;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "rocfft-1.0.13.1188-65699a2-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "ubuntu-18.04_amd64-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "ubuntu-18.04_amd64")
set(CPACK_TOPLEVEL_TAG "ubuntu-18.04_amd64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/ugrad/ugrad003/roctosycl/rocFFT/builddir/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
